trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

variables:
  ref: $(Build.SourceBranch)
  commit: $(Build.SourceVersion)
  version: ''
  repository: 'focal-freedom-236620/darcy-ai-explorer'
  publicRepository: 'darcyai/darcy-ai-explorer'
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

stages:
- stage: Preflight
  jobs:
  - job: "Build_UI"
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    - script: |
        npm i -g npm
        npm i
        npm run build
      displayName: 'Build ui bundle'
      workingDirectory: ./src/ui
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/src/ui/build'
        ArtifactName: ui_build
      displayName: 'Publish ui build'

- stage: Build
  jobs:
  - job: ARM64
    pool: build-farm-coral
    steps:
    - template: pipeline/setversion.yaml
    - template: pipeline/setup-bundle.yaml
    - task: Docker@2
      displayName: 'Publish ARM Docker Image'
      inputs:
        containerRegistry: 'Edgeworx GCP'
        repository: '$(repository)-arm64'
        command: 'buildAndPush'
        Dockerfile: './Dockerfile.bundled'
        buildContext: '.'
        tags: |
          $(version)
          latest
    - task: Docker@2
      displayName: Login to Dockerhub
      condition: eq(variables['isRelease'], true)
      inputs:
        command: login
        containerRegistry: DarcyAI-Dockerhub
    - script: |
        docker tag gcr.io/$(repository)-arm64:$(version) $(publicRepository)-arm64:$(version)
        docker push $(publicRepository)-arm64:$(version)
      displayName: 'Publish ARM Docker Image'
      condition: eq(variables['isRelease'], true)
  - job: ARM32
    pool: build-farm-rpi4
    steps:
    - template: pipeline/setversion.yaml
    - template: pipeline/setup-bundle.yaml
    - task: Docker@2
      displayName: 'Publish ARM Docker Image'
      inputs:
        containerRegistry: 'Edgeworx GCP'
        repository: '$(repository)-arm32'
        command: 'buildAndPush'
        Dockerfile: './Dockerfile.bundled'
        buildContext: '.'
        tags: |
          $(version)
          latest
    - task: Docker@2
      displayName: Login to Dockerhub
      condition: eq(variables['isRelease'], true)
      inputs:
        command: login
        containerRegistry: DarcyAI-Dockerhub
    - script: |
        docker tag gcr.io/$(repository)-arm32:$(version) $(publicRepository)-arm32:$(version)
        docker push $(publicRepository)-arm32:$(version)
      displayName: 'Publish ARM Docker Image'
      condition: eq(variables['isRelease'], true)

  - job: x86
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - template: pipeline/setversion.yaml
    - template: pipeline/setup-bundle.yaml
    - task: Docker@2
      displayName: 'Publish x86 Docker Image'
      inputs:
        containerRegistry: 'Edgeworx GCP'
        repository: '$(repository)-x86'
        command: 'buildAndPush'
        Dockerfile: './Dockerfile.bundled'
        buildContext: '.'
        tags: |
          $(version)
          latest
    - task: Docker@2
      displayName: Login to Dockerhub
      condition: eq(variables['isRelease'], true)
      inputs:
        command: login
        containerRegistry: DarcyAI-Dockerhub
    - script: |
        docker tag gcr.io/$(repository)-x86:$(version) $(publicRepository)-x86:$(version)
        docker push $(publicRepository)-x86:$(version)
      displayName: 'Publish x86 Docker Image'
      condition: eq(variables['isRelease'], true)
- stage: Publish
  condition: eq(variables['isRelease'], true)
  jobs:
  - job: Publish_manifest
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - template: pipeline/setversion.yaml
    - task: Docker@2
      displayName: Login to Dockerhub
      inputs:
        command: login
        containerRegistry: DarcyAI-Dockerhub
    - script: |
        docker pull $(publicRepository)-x86:$(version)
        docker pull $(publicRepository)-arm32:$(version)
        docker pull $(publicRepository)-arm64:$(version)
      displayName: 'Pull $(publicRepository) amd64, arm32v7, and arm64v8 docker images'
    - script: |
        docker manifest create \
          $(publicRepository):$(version) \
          --amend $(publicRepository)-x86:$(version) \
          --amend $(publicRepository)-arm32:$(version) \
          --amend $(publicRepository)-arm64:$(version)
      displayName: 'Create $(publicRepository) image manifest'
    - script: |
        docker manifest push $(publicRepository):$(version)
      displayName: 'Push $(publicRepository) image manifest'