FROM darcyai/darcy-ai-coral:dev

RUN apt-get update -y
RUN apt-get install -y libzbar0

RUN python3 -m pip install --upgrade darcyai-engine
RUN python3 -m pip install --upgrade darcyai-coral
RUN python3 -m pip install --upgrade flask_cors
RUN python3 -m pip install --upgrade pyzbar==0.1.8

WORKDIR /src

COPY src/ui/build ./ui/build/
COPY src/pipeline ./pipeline/
COPY src/main.py ./main.py

ENTRYPOINT ["python3", "-u", "./main.py"]
